version: 2.1

jobs:
  automated-api-tests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - run:
          name: Login using your API key
          command: $PMAK-63e176afeaf3084e7d75cd49-7081ab8660919f5b24b29ecb0ee8610bc6
      - run: |
            postman collection run "3862417-ad545b67-9576-4372-bd12-aa68d104045d" -e "3862417-a283d708-a19a-4185-9545-1d5086a45ab4" --integration-id "132678-${CIRCLE_WORKFLOW_JOB_ID}"

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests
